[tox]
envlist =
    py{310, 311, 312, 313, 314}{,-dev}

[testenv]
extras =
    test
deps =
    dev: git+https://github.com/guaix-ucm/numina@main
commands =
    pytest {posargs}

[testenv:docs]
changedir = doc
description = build documentation
extras =
    docs
commands = sphinx-build -W -b html -d {envtmpdir}/doctrees . {envtmpdir}/html

[testenv:cov]
description = test coverage
deps =
    pytest-cov
commands = pytest --cov=megaradrp --cov-report=term-missing {posargs}

[testenv:codestyle]
changedir = src
description = check code style with flake8
skip_install = true
deps = flake8
commands = flake8 megaradrp --count
