name: MEGARA
configurations:
  values:
  - 9a86b2b2-3f7d-48ec-8f4f-3780ec967c90
  - 4fd05b24-2ed9-457b-b563-a3c618bb1d4c
  - 66f2283e-3049-4d4b-8ef1-14d62fcb611d
  - ca3558e3-e50d-4bbc-86bd-da50a0998a48
  default: ca3558e3-e50d-4bbc-86bd-da50a0998a48
datamodel: megaradrp.datamodel.MegaraDataModel
modes:
- name: Success
  summary: A mode where the recipe successes
  description: A mode where the recipe successes, used for testing
  key: MegaraSuccess
  tagger: null
- name: Fail
  summary: A mode where the recipe fails
  description: A mode where the recipe fails, used for testing
  key: MegaraFail
  tagger: null
- name: Bias Image
  summary: Recipe to process bias images
  description: Recipe to process bias images
  key: MegaraBiasImage
  tagger: null
- name: Dark current Image
  summary: Summary of Dark current Image
  description: Lines and mode lines
  key: MegaraDarkImage
  tagger: null
- name: Fiber Flat Image
  summary: Summary of Fiber Flat Image
  description: Lines and mode lines
  key: MegaraFiberFlatImage
  tagger: megaradrp.taggers.tagger_base_image
- name: Image with the fiber MOS
  summary: Summary of Fiber MOS image
  description: Lines and mode lines
  key: MegaraMosImage
  tagger: megaradrp.taggers.tagger_base_image
- name: Trace Map
  summary: Summary of Fiber MOS image
  description: Lines and mode lines
  key: MegaraTraceMap
  tagger: megaradrp.taggers.tagger_base_image
- name: Arc Calibration
  summary: Summary of Arc Calibration
  description: Process an Arc image
  key: MegaraArcCalibration
  tagger: ['vph', 'insmode', 'speclamp']
- name: Bad Pixel Mask
  summary: Bad Pixel Mask
  description: Bad Pixels
  key: MegaraBadPixelMask
  tagger: null
- name: Slit Flat
  summary: Slit Flat
  description: Slit Flat
  key: MegaraSlitFlat
  tagger: megaradrp.taggers.tagger_base_image
- name: ModelMap
  summary: Computes a ModelMap
  description: Computes a ModelMap from FlatImages
  key: MegaraModelMap
  tagger: megaradrp.taggers.tagger_base_image
- key: MegaraFocusSpectrograph
  name: Focus Spectrograph
  tagger: megaradrp.taggers.tagger_base_image
  validator: megaradrp.validators.validate_focus
- name: Twillight fiber flat
  summary: Twillight fiber flat spectrum
  description: Twillight fiber flat spectrum
  key: MegaraTwilightFlatImage
  tagger: megaradrp.taggers.tagger_base_image
- name: Image with the LCB
  summary: Image with the LCB
  description: Image with the LCB
  key: MegaraLcbImage
  tagger: megaradrp.taggers.tagger_base_image
- name: Image with the MOS
  summary: Image with the MOS
  description: Image with the MOS
  key: MegaraMosImage
  tagger: megaradrp.taggers.tagger_base_image
- name: Extinction Star Recipe
  summary: Extinction Star Recipe
  description: Extinction Star Recipe
  key: MegaraExtinctionStar
  tagger: megaradrp.taggers.tagger_base_image
- name: LCB Standard Recipe
  summary: LCB Standard Recipe
  description: LCB Standard Recipe
  key: MegaraLcbStdStar
  tagger: megaradrp.taggers.tagger_base_image
- name: MOS Standard Recipe
  summary: MOS Standard Recipe
  description: MOS Standard Recipe
  key: MegaraMosStdStar
  tagger: megaradrp.taggers.tagger_base_image
- name: Sensivity Star Recipe
  summary: Sensivity Star Recipe
  description: Sensivity Star Recipe
  key: MegaraSensitivityStar
  tagger: megaradrp.taggers.tagger_base_image
- name: Linearity test
  summary: Test the linearity of the MEGARA detector
  description: Test the linearity of the MEGARA detector
  key: MegaraLinearirtyTest
  tagger: megaradrp.taggers.tagger_base_image
- name: Telescope Focus
  summary: Telescope Focus
  description: Telescope Focus
  key: MegaraFocusTelescope
  tagger: megaradrp.taggers.tagger_base_image
- name: Acquisition with the LCB IFU
  summary: Acquisition with the LCB IFU
  description: Acquisition with the LCB IFU
  key: MegaraLcbAcquisition
  tagger: megaradrp.taggers.tagger_base_image
- name: Acquisition with the Fiber MOS
  summary: Acquisition with the Fiber MOS
  description: Acquisition with the Fiber MOS
  key: MegaraMosAcquisition
  tagger: megaradrp.taggers.tagger_base_image
pipelines:
  default:
    version: 1
    products:
      MasterBias: megaradrp.types.MasterBias
      MasterBPM: megaradrp.types.MasterBPM
      MasterDark: megaradrp.types.MasterDark
      WavelengthCalibration: megaradrp.products.WavelengthCalibration
      MasterSlitFlat: megaradrp.types.MasterSlitFlat
      TraceMap: megaradrp.products.TraceMap
      ModelMap: megaradrp.products.ModelMap
      MasterFiberFlat: megaradrp.types.MasterFiberFlat
      MasterTwilightFlat: megaradrp.types.MasterTwilightFlat
      LinesCatalog: numina.core.products.LinesCatalog
    provides:
      - name: MasterBias
        mode: MegaraBiasImage
        field: master_bias
      - name: MasterBPM
        mode: MegaraBadPixelMask
        field: master_bpm
      - name: MasterDark
        mode: MegaraDarkImage
        field: master_dark
      - name: WavelengthCalibration
        mode: MegaraArcCalibration
        field: master_wlcalib
      - name: MasterSlitFlat
        mode: MegaraSlitFlat
        field: master_slitflat
      - name: TraceMap
        mode: MegaraTraceMap
        field: master_traces
      - name: MasterFiberFlat
        mode: MegaraFiberFlatImage
        field: master_fiberflat
      - name: MasterTwilightFlat
        mode: MegaraTwilightFlatImage
        field: master_twilightflat
      - name: ModelMap
        mode: MegaraModelMap
        field: master_model
    recipes:
      MegaraSuccess: numina.core.utils.AlwaysSuccessRecipe
      MegaraFail: 
         class: numina.core.utils.AlwaysFailRecipe 
         args: [1,2,3] 
         keys: {key1: 1, key2: 2} 
         state: {}
      MegaraBadPixelMask: megaradrp.recipes.calibration.bpm.BadPixelsMaskRecipe
      MegaraLinearityTest: megaradrp.recipes.calibration.linearity.LinearityTestRecipe
      MegaraBiasImage: megaradrp.recipes.calibration.bias.BiasRecipe
      MegaraDarkImage: megaradrp.recipes.calibration.dark.DarkRecipe
      MegaraArcCalibration: megaradrp.recipes.calibration.arc.ArcCalibrationRecipe
      MegaraSlitFlat: megaradrp.recipes.calibration.slitflat.SlitFlatRecipe
      MegaraTraceMap: megaradrp.recipes.calibration.trace.TraceMapRecipe
      MegaraModelMap: megaradrp.recipes.calibration.modelmap.ModelMapRecipe
      MegaraFiberFlatImage: megaradrp.recipes.calibration.flat.FiberFlatRecipe
      MegaraTwilightFlatImage: megaradrp.recipes.calibration.twilight.TwilightFiberFlatRecipe
      MegaraFocusSpectrograph: megaradrp.recipes.auxiliary.focusspec.FocusSpectrographRecipe
      MegaraFocusTelescope: megaradrp.recipes.auxiliary.focustel.FocusTelescopeRecipe
      MegaraLcbAcquisition: megaradrp.recipes.auxiliary.acquisitionlcb.AcquireLCBRecipe
      MegaraLcbImage: megaradrp.recipes.scientific.lcb.LCBImageRecipe
      MegaraLcbStdStar: megaradrp.recipes.calibration.lcbstdstar.LCBStandardRecipe
      MegaraMosAcquisition: megaradrp.recipes.auxiliary.acquisitionmos.AcquireMOSRecipe
      MegaraMosImage: megaradrp.recipes.scientific.mos.MOSImageRecipe
      MegaraMosStdStar: megaradrp.recipes.calibration.mosstdstar.MOSStandardRecipe
      MegaraExtinctionStar: megaradrp.recipes.combined.extinctionstar.Recipe
      MegaraSensitivityStar: megaradrp.recipes.combined.sensstar.Recipe


